PATCH http://localhost:3000/posts
content-type: application/json

{
    "id": 4,
    "title": "What's new with NestJS With Vue 3",
    "postType": "post",
    "content": "just  a content",
    "tags": [6, 7, 8]
}