POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6Im51enVtYWtpQGdtYWlsLmNvbSIsImlhdCI6MTc3MDQwNTYzOCwiZXhwIjoxNzcwNDA5MjM4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.dr5gdQz8B2BKJh2JuKNxv8ICbLs4VTinLaAUyz1uEy0

{
    "title": "Quantum Computing for Web Developers",
    "postType": "post",
    "slug": "quantum-computing-web-dev",
    "status": "published",
    "content": "Is it time to learn Q# or should we wait for better JS bridges?",
    "schema": "{\r\n \"@context\": \"https://schema.org\" \r\n}",
    "featuredImageUrl": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb",
    "publishOn": "2026-02-28T12:00:00+0000",
    "metaOptions": { "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}" },
    "tags": [5, 6, 7]
  }