POST https//portfolioback-end-production.up.railway.app/users/
Content-Type: application/json

{
  "firstName": "Brahim",
  "lastName": "Nachate",
  "admin": true,
  "email": "nachatim@gmail.com",
  "password": "p1a#ssword"
}
POST http://localhost:3500/users
Content-Type: application/json

{
  "firstName": "Brahim",
  "lastName": "Nachate",
  "admin": true,
  "email": "nachatim@gmail.com",
  "password": "p1a#ssword",
  "job": "Développeur Fullstack",
  "title": "Passionné par l'architecture logicielle",
  "description": "Développeur avec 5 ans d'expérience sur NestJS et React.",
  "githubUrl": "https://github.com/jeandupont",
  "linkedinUrl": "https://linkedin.com/in/jeandupont"
}

POST http://localhost:3500/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6Im51enVtYWtpQGdtYWlsLmNvbSIsImlhdCI6MTc3MDIzMTgzNCwiZXhwIjoxNzcwMjM1NDM0LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.8Ris7bvYFe5P_NZUlxMa6RgyHSPsVDgef-lTrEby484

{
  "users": [
    {
      "firstName": "Lucas",
      "lastName": "Morel",
      "email": "l.morel@example.com",
      "password": "p1a#ssword"
    },
    {
      "firstName": "Sarah",
      "lastName": "Koné",
      "email": "s.kone@test.io",
      "password": "p1a#ssword"
    },
    {
      "firstName": "Julien",
      "lastName": "Bernard",
      "email": "jbernard@hub.fr",
      "password": "p1a#ssword"
    },
    {
      "firstName": "Sophie",
      "lastName": "Vidal",
      "email": "svidal@agency.com",
      "password": "p1a#ssword"
    },
    {
      "firstName": "Thomas",
      "lastName": "Dubois",
      "email": "t.dubois@provider.net",
      "password": "p1a#ssword"
    }
  ]
}