POST http://localhost:3500/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibmFjaGF0ZS5icmFoaW1AZ21haWwuY29tIiwiaWF0IjoxNzcwNzYyODI0LCJleHAiOjE3NzA3NjY0MjQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.TP5H-h3W37L90XIRTM_zsntUU8fUWPaJ4a9_TDswLps

{
  "name": "Jean Bernard",
  "email": "claireobscure@gmail.com",
  "subject": "Nous vous voulons immediatemment",
  "message": "Venez travailler avec nous svp !"
  }