POST http://localhost:3500/tags
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibmFjaGF0ZS5icmFoaW1AZ21haWwuY29tIiwiaWF0IjoxNzcxNjAwNzM2LCJleHAiOjE3NzE2MDQzMzYsImF1ZCI6ImxvY2FsaG9zdDozNTAwIiwiaXNzIjoibG9jYWxob3N0OjM1MDAifQ.QklYYZ8Jr_ryEAQGwvd7ZULf2mOgsziWggnnQZ1ejuk

{
  "name": "Adobe Dreamweaver"
}
