POST http://localhost:3500/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibmFjaGF0ZS5icmFoaW1AZ21haWwuY29tIiwiaWF0IjoxNzcyODg3NDc1LCJleHAiOjE3NzI4OTEwNzUsImF1ZCI6ImxvY2FsaG9zdDozNTAwIiwiaXNzIjoibG9jYWxob3N0OjM1MDAifQ.Q95SlDmomydMlbR7Lis-0KxuEJOjsf8hyT-dqu1c7Gw
{
    "title": "Quantum Computing for Web Developers",
    "description": "Is it time to learn Q# or should we wait for better JS bridges?",
    "projectImageUrl": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb",
    "githubUrl": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb",
    "position": 1,
    "tags": []
  }